In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df = pd.read_csv("../data/imdb_eda.csv")

display(df.head())
print(df.shape)

,name,year,duration,genre,rating,votes,director,actor_1,actor_2,actor_3,log_votes,main_genre,lead_actor,decade
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia,NaN,Drama,Manmauji,NaN
1,#Gadhvi (He thought he was Gandhi),2019.0,109.0,Drama,7.0,8.0,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,2.197225,Drama,Rasika Dugal,2010.0
2,#Homecoming,2021.0,90.0,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana,NaN,Drama,Sayani Gupta,2020.0
3,#Yaaram,2019.0,110.0,"Comedy, Romance",4.4,35.0,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,3.583519,Comedy,Prateik,2010.0
4,...And Once Again,2010.0,105.0,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali,NaN,Drama,Rajat Kapoor,2010.0

(15503, 14)

In [3]:
print(df.columns.tolist())

['name', 'year', 'duration', 'genre', 'rating', 'votes', 'director', 'actor_1', 'actor_2', 'actor_3', 'log_votes', 'main_genre', 'lead_actor', 'decade']

In [4]:
required_cols = [
    "name", "year", "duration", "genre", "main_genre",
    "rating", "votes", "director", "actor_1", "actor_2", "actor_3"
]

df = df[required_cols].copy()

display(df.head())

,name,year,duration,genre,main_genre,rating,votes,director,actor_1,actor_2,actor_3
0,,NaN,NaN,Drama,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),2019.0,109.0,Drama,Drama,7.0,8.0,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,2021.0,90.0,"Drama, Musical",Drama,NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,2019.0,110.0,"Comedy, Romance",Comedy,4.4,35.0,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,2010.0,105.0,Drama,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali

In [5]:
text_cols = ["name", "genre", "main_genre", "director", "actor_1", "actor_2", "actor_3"]

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace("nan", np.nan)

df["rating"] = pd.to_numeric(df["rating"], errors="coerce")
df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["duration"] = pd.to_numeric(df["duration"], errors="coerce")
df["votes"] = pd.to_numeric(df["votes"], errors="coerce")

display(df.head())

,name,year,duration,genre,main_genre,rating,votes,director,actor_1,actor_2,actor_3
0,,NaN,NaN,Drama,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),2019.0,109.0,Drama,Drama,7.0,8.0,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,2021.0,90.0,"Drama, Musical",Drama,NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,2019.0,110.0,"Comedy, Romance",Comedy,4.4,35.0,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,2010.0,105.0,Drama,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali

In [6]:
df = df.dropna(subset=["rating"])

print("Shape after removing rows without rating:", df.shape)

Shape after removing rows without rating: (7919, 11)

In [7]:
df["duration_missing"] = df["duration"].isnull().astype(int)
df["votes_missing"] = df["votes"].isnull().astype(int)
df["year_missing"] = df["year"].isnull().astype(int)
df["director_missing"] = df["director"].isnull().astype(int)
df["actor_1_missing"] = df["actor_1"].isnull().astype(int)

display(df.head())

,name,year,duration,genre,main_genre,rating,votes,director,actor_1,actor_2,actor_3,duration_missing,votes_missing,year_missing,director_missing,actor_1_missing
1,#Gadhvi (He thought he was Gandhi),2019.0,109.0,Drama,Drama,7.0,8.0,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,0,0,0,0,0
3,#Yaaram,2019.0,110.0,"Comedy, Romance",Comedy,4.4,35.0,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,0,0,0,0,0
5,...Aur Pyaar Ho Gaya,1997.0,147.0,"Comedy, Drama, Musical",Comedy,4.7,827.0,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,0,0,0,0,0
6,...Yahaan,2005.0,142.0,"Drama, Romance, War",Drama,7.4,1086.0,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma,0,0,0,0,0
8,?: A Question Mark,2012.0,82.0,"Horror, Mystery, Thriller",Horror,5.6,326.0,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia,0,0,0,0,0

In [8]:
df["duration"] = df["duration"].fillna(df["duration"].median())
df["votes"] = df["votes"].fillna(df["votes"].median())
df["year"] = df["year"].fillna(df["year"].median())

print(df[["duration", "votes", "year"]].isnull().sum())

duration    0
votes       0
year        0
dtype: int64

In [9]:
categorical_cols = ["genre", "main_genre", "director", "actor_1", "actor_2", "actor_3"]

for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

display(df.head())

,name,year,duration,genre,main_genre,rating,votes,director,actor_1,actor_2,actor_3,duration_missing,votes_missing,year_missing,director_missing,actor_1_missing
1,#Gadhvi (He thought he was Gandhi),2019.0,109.0,Drama,Drama,7.0,8.0,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,0,0,0,0,0
3,#Yaaram,2019.0,110.0,"Comedy, Romance",Comedy,4.4,35.0,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,0,0,0,0,0
5,...Aur Pyaar Ho Gaya,1997.0,147.0,"Comedy, Drama, Musical",Comedy,4.7,827.0,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,0,0,0,0,0
6,...Yahaan,2005.0,142.0,"Drama, Romance, War",Drama,7.4,1086.0,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma,0,0,0,0,0
8,?: A Question Mark,2012.0,82.0,"Horror, Mystery, Thriller",Horror,5.6,326.0,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia,0,0,0,0,0

In [10]:
CURRENT_YEAR = 2026

df["movie_age"] = CURRENT_YEAR - df["year"]

display(df[["name", "year", "movie_age"]].head())

                                 name    year  movie_age
1  #Gadhvi (He thought he was Gandhi)  2019.0        7.0
3                             #Yaaram  2019.0        7.0
5                ...Aur Pyaar Ho Gaya  1997.0       29.0
6                           ...Yahaan  2005.0       21.0
8                  ?: A Question Mark  2012.0       14.0

In [11]:
df["genre_count"] = df["genre"].apply(lambda x: len(str(x).split(",")) if x != "Unknown" else 0)

display(df[["name", "genre", "genre_count"]].head())

                                 name                      genre  genre_count
1  #Gadhvi (He thought he was Gandhi)                      Drama            1
3                             #Yaaram            Comedy, Romance            2
5                ...Aur Pyaar Ho Gaya     Comedy, Drama, Musical            3
6                           ...Yahaan        Drama, Romance, War            3
8                  ?: A Question Mark  Horror, Mystery, Thriller            3

In [12]:
def runtime_category(minutes):
    if minutes < 90:
        return "Short"
    elif minutes <= 150:
        return "Medium"
    else:
        return "Long"

df["runtime_category"] = df["duration"].apply(runtime_category)

display(df[["name", "duration", "runtime_category"]].head())

                                 name  duration runtime_category
1  #Gadhvi (He thought he was Gandhi)     109.0           Medium
3                             #Yaaram     110.0           Medium
5                ...Aur Pyaar Ho Gaya     147.0           Medium
6                           ...Yahaan     142.0           Medium
8                  ?: A Question Mark      82.0            Short

In [13]:
df["log_votes"] = np.log1p(df["votes"])

display(df[["name", "votes", "log_votes"]].head())

                                 name   votes  log_votes
1  #Gadhvi (He thought he was Gandhi)     8.0   2.197225
3                             #Yaaram    35.0   3.583519
5                ...Aur Pyaar Ho Gaya   827.0   6.719013
6                           ...Yahaan  1086.0   6.991177
8                  ?: A Question Mark   326.0   5.789960

In [14]:
vote_75 = df["votes"].quantile(0.75)
vote_90 = df["votes"].quantile(0.90)

df["popular_movie"] = (df["votes"] >= vote_75).astype(int)
df["highly_popular_movie"] = (df["votes"] >= vote_90).astype(int)
df["vote_percentile"] = df["votes"].rank(pct=True)

display(df[["name", "votes", "popular_movie", "highly_popular_movie", "vote_percentile"]].head())

,name,votes,popular_movie,highly_popular_movie,vote_percentile
1,#Gadhvi (He thought he was Gandhi),8.0,0,0,0.090289
3,#Yaaram,35.0,0,0,0.412994
5,...Aur Pyaar Ho Gaya,827.0,1,0,0.811529
6,...Yahaan,1086.0,1,0,0.832176
8,?: A Question Mark,326.0,0,0,0.728690

In [15]:
director_experience = df["director"].value_counts()

df["director_experience"] = df["director"].map(director_experience)

display(df[["name", "director", "director_experience"]].head())

                                 name        director  director_experience
1  #Gadhvi (He thought he was Gandhi)   Gaurav Bakshi                    1
3                             #Yaaram      Ovais Khan                    1
5                ...Aur Pyaar Ho Gaya    Rahul Rawail                   17
6                           ...Yahaan  Shoojit Sircar                    7
8                  ?: A Question Mark   Allyson Patel                    1

In [16]:
director_avg_rating = df.groupby("director")["rating"].mean()

df["director_avg_rating"] = df["director"].map(director_avg_rating)

display(df[["name", "director", "director_avg_rating"]].head())

                                 name        director  director_avg_rating
1  #Gadhvi (He thought he was Gandhi)   Gaurav Bakshi             7.000000
3                             #Yaaram      Ovais Khan             4.400000
5                ...Aur Pyaar Ho Gaya    Rahul Rawail             5.358824
6                           ...Yahaan  Shoojit Sircar             7.500000
8                  ?: A Question Mark   Allyson Patel             5.600000

In [17]:
actor_experience = df["actor_1"].value_counts()

df["lead_actor_experience"] = df["actor_1"].map(actor_experience)

display(df[["name", "actor_1", "lead_actor_experience"]].head())

                                 name          actor_1  lead_actor_experience
1  #Gadhvi (He thought he was Gandhi)     Rasika Dugal                      2
3                             #Yaaram          Prateik                      5
5                ...Aur Pyaar Ho Gaya       Bobby Deol                     18
6                           ...Yahaan  Jimmy Sheirgill                     25
8                  ?: A Question Mark        Yash Dave                      1

In [18]:
actor_avg_rating = df.groupby("actor_1")["rating"].mean()

df["lead_actor_avg_rating"] = df["actor_1"].map(actor_avg_rating)

display(df[["name", "actor_1", "lead_actor_avg_rating"]].head())

                                 name          actor_1  lead_actor_avg_rating
1  #Gadhvi (He thought he was Gandhi)     Rasika Dugal               6.850000
3                             #Yaaram          Prateik               5.420000
5                ...Aur Pyaar Ho Gaya       Bobby Deol               4.788889
6                           ...Yahaan  Jimmy Sheirgill               5.356000
8                  ?: A Question Mark        Yash Dave               5.600000

In [19]:
genre_frequency = df["main_genre"].value_counts(normalize=True)

df["genre_frequency"] = df["main_genre"].map(genre_frequency)

display(df[["name", "main_genre", "genre_frequency"]].head())

                                 name main_genre  genre_frequency
1  #Gadhvi (He thought he was Gandhi)      Drama         0.319737
3                             #Yaaram     Comedy         0.150271
5                ...Aur Pyaar Ho Gaya     Comedy         0.150271
6                           ...Yahaan      Drama         0.319737
8                  ?: A Question Mark     Horror         0.023740

In [20]:
runtime_dummies = pd.get_dummies(df["runtime_category"], prefix="runtime", drop_first=False)

df = pd.concat([df, runtime_dummies], axis=1)

display(df.head())

,name,year,duration,genre,main_genre,rating,votes,director,actor_1,actor_2,actor_3,duration_missing,votes_missing,year_missing,director_missing,actor_1_missing,movie_age,genre_count,runtime_category,log_votes,popular_movie,highly_popular_movie,vote_percentile,director_experience,director_avg_rating,lead_actor_experience,lead_actor_avg_rating,genre_frequency,runtime_Long,runtime_Medium,runtime_Short
1,#Gadhvi (He thought he was Gandhi),2019.0,109.0,Drama,Drama,7.0,8.0,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,0,0,0,0,0,7.0,1,Medium,2.197225,0,0,0.090289,1,7.000000,2,6.850000,0.319737,False,True,False
3,#Yaaram,2019.0,110.0,"Comedy, Romance",Comedy,4.4,35.0,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,0,0,0,0,0,7.0,2,Medium,3.583519,0,0,0.412994,1,4.400000,5,5.420000,0.150271,False,True,False
5,...Aur Pyaar Ho Gaya,1997.0,147.0,"Comedy, Drama, Musical",Comedy,4.7,827.0,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,0,0,0,0,0,29.0,3,Medium,6.719013,1,0,0.811529,17,5.358824,18,4.788889,0.150271,False,True,False
6,...Yahaan,2005.0,142.0,"Drama, Romance, War",Drama,7.4,1086.0,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma,0,0,0,0,0,21.0,3,Medium,6.991177,1,0,0.832176,7,7.500000,25,5.356000,0.319737,False,True,False
8,?: A Question Mark,2012.0,82.0,"Horror, Mystery, Thriller",Horror,5.6,326.0,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia,0,0,0,0,0,14.0,3,Short,5.789960,0,0,0.728690,1,5.600000,1,5.600000,0.023740,False,False,True

In [21]:
genre_dummies = df["genre"].str.get_dummies(sep=",")
genre_dummies.columns = genre_dummies.columns.str.strip().str.lower().str.replace(" ", "_")
genre_dummies = genre_dummies.add_prefix("genre_")

df = pd.concat([df, genre_dummies], axis=1)

display(df.head())

,name,year,duration,genre,main_genre,rating,votes,director,actor_1,actor_2,actor_3,duration_missing,votes_missing,year_missing,director_missing,actor_1_missing,movie_age,genre_count,runtime_category,log_votes,popular_movie,highly_popular_movie,vote_percentile,director_experience,director_avg_rating,lead_actor_experience,lead_actor_avg_rating,genre_frequency,runtime_Long,runtime_Medium,runtime_Short,genre_action,genre_adventure,genre_biography,genre_comedy,genre_crime,genre_drama,genre_family,genre_fantasy,genre_history,genre_horror,genre_music,genre_musical,genre_mystery,genre_news,genre_romance,genre_sci-fi,genre_sport,genre_thriller,genre_war,genre_western,genre_action,genre_adventure,genre_animation,genre_biography,genre_comedy,genre_crime,genre_documentary,genre_drama,genre_family,genre_fantasy,genre_history,genre_horror,genre_music,genre_musical,genre_mystery,genre_romance,genre_sci-fi,genre_sport,genre_thriller,genre_unknown,genre_war
1,#Gadhvi (He thought he was Gandhi),2019.0,109.0,Drama,Drama,7.0,8.0,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,0,0,0,0,0,7.0,1,Medium,2.197225,0,0,0.090289,1,7.000000,2,6.850000,0.319737,False,True,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3,#Yaaram,2019.0,110.0,"Comedy, Romance",Comedy,4.4,35.0,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,0,0,0,0,0,7.0,2,Medium,3.583519,0,0,0.412994,1,4.400000,5,5.420000,0.150271,False,True,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,...Aur Pyaar Ho Gaya,1997.0,147.0,"Comedy, Drama, Musical",Comedy,4.7,827.0,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,0,0,0,0,0,29.0,3,Medium,6.719013,1,0,0.811529,17,5.358824,18,4.788889,0.150271,False,True,False,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,...Yahaan,2005.0,142.0,"Drama, Romance, War",Drama,7.4,1086.0,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma,0,0,0,0,0,21.0,3,Medium,6.991177,1,0,0.832176,7,7.500000,25,5.356000,0.319737,False,True,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
8,?: A Question Mark,2012.0,82.0,"Horror, Mystery, Thriller",Horror,5.6,326.0,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia,0,0,0,0,0,14.0,3,Short,5.789960,0,0,0.728690,1,5.600000,1,5.600000,0.023740,False,False,True,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [22]:
print("Final shape:", df.shape)

display(df.head())

display(df.info())

Final shape: (7919, 72)

,name,year,duration,genre,main_genre,rating,votes,director,actor_1,actor_2,actor_3,duration_missing,votes_missing,year_missing,director_missing,actor_1_missing,movie_age,genre_count,runtime_category,log_votes,popular_movie,highly_popular_movie,vote_percentile,director_experience,director_avg_rating,lead_actor_experience,lead_actor_avg_rating,genre_frequency,runtime_Long,runtime_Medium,runtime_Short,genre_action,genre_adventure,genre_biography,genre_comedy,genre_crime,genre_drama,genre_family,genre_fantasy,genre_history,genre_horror,genre_music,genre_musical,genre_mystery,genre_news,genre_romance,genre_sci-fi,genre_sport,genre_thriller,genre_war,genre_western,genre_action,genre_adventure,genre_animation,genre_biography,genre_comedy,genre_crime,genre_documentary,genre_drama,genre_family,genre_fantasy,genre_history,genre_horror,genre_music,genre_musical,genre_mystery,genre_romance,genre_sci-fi,genre_sport,genre_thriller,genre_unknown,genre_war
1,#Gadhvi (He thought he was Gandhi),2019.0,109.0,Drama,Drama,7.0,8.0,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,0,0,0,0,0,7.0,1,Medium,2.197225,0,0,0.090289,1,7.000000,2,6.850000,0.319737,False,True,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3,#Yaaram,2019.0,110.0,"Comedy, Romance",Comedy,4.4,35.0,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,0,0,0,0,0,7.0,2,Medium,3.583519,0,0,0.412994,1,4.400000,5,5.420000,0.150271,False,True,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,...Aur Pyaar Ho Gaya,1997.0,147.0,"Comedy, Drama, Musical",Comedy,4.7,827.0,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,0,0,0,0,0,29.0,3,Medium,6.719013,1,0,0.811529,17,5.358824,18,4.788889,0.150271,False,True,False,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,...Yahaan,2005.0,142.0,"Drama, Romance, War",Drama,7.4,1086.0,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma,0,0,0,0,0,21.0,3,Medium,6.991177,1,0,0.832176,7,7.500000,25,5.356000,0.319737,False,True,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
8,?: A Question Mark,2012.0,82.0,"Horror, Mystery, Thriller",Horror,5.6,326.0,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia,0,0,0,0,0,14.0,3,Short,5.789960,0,0,0.728690,1,5.600000,1,5.600000,0.023740,False,False,True,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

<class 'pandas.core.frame.DataFrame'>
Index: 7919 entries, 1 to 15502
Data columns (total 72 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   name                   7919 non-null   object
 1   year                   7919 non-null   float64
 2   duration               7919 non-null   float64
 3   genre                  7919 non-null   object
 4   main_genre             7919 non-null   object
 5   rating                 7919 non-null   float64
 6   votes                  7919 non-null   float64
 7   director               7919 non-null   object
 8   actor_1                7919 non-null   object
 9   actor_2                7919 non-null   object
 10  actor_3                7919 non-null   object
 11  duration_missing       7919 non-null   int64
 12  votes_missing          7919 non-null   int64
 13  year_missing           7919 non-null   int64
 14  director_missing       7919 non-null   int64
 15  actor_1_missing        7919 non-null   int64
 16  movie_age              7919 non-null   float64
 17  genre_count            7919 non-null   int64
 18  runtime_category       7919 non-null   object
 19  log_votes              7919 non-null   float64
 20  popular_movie          7919 non-null   int64
 21  highly_popular_movie   7919 non-null   int64
 22  vote_percentile        7919 non-null   float64
 23  director_experience    7919 non-null   int64
 24  director_avg_rating    7919 non-null   float64
 25  lead_actor_experience  7919 non-null   int64
 26  lead_actor_avg_rating  7919 non-null   float64
 27  genre_frequency        7919 non-null   float64
 28  runtime_Long           7919 non-null   bool
 29  runtime_Medium         7919 non-null   bool
 30  runtime_Short          7919 non-null   bool
 31  genre_action           7919 non-null   int64
 32  genre_adventure        7919 non-null   int64
 33  genre_biography        7919 non-null   int64
 34  genre_comedy           7919 non-null   int64
 35  genre_crime            7919 non-null   int64
 36  genre_drama            7919 non-null   int64
 37  genre_family           7919 non-null   int64
 38  genre_fantasy          7919 non-null   int64
 39  genre_history          7919 non-null   int64
 40  genre_horror           7919 non-null   int64
 41  genre_music            7919 non-null   int64
 42  genre_musical          7919 non-null   int64
 43  genre_mystery          7919 non-null   int64
 44  genre_news             7919 non-null   int64
 45  genre_romance          7919 non-null   int64
 46  genre_sci-fi           7919 non-null   int64
 47  genre_sport            7919 non-null   int64
 48  genre_thriller         7919 non-null   int64
 49  genre_war              7919 non-null   int64
 50  genre_western          7919 non-null   int64
 51  genre_action           7919 non-null   int64
 52  genre_adventure        7919 non-null   int64
 53  genre_animation        7919 non-null   int64
 54  genre_biography        7919 non-null   int64
 55  genre_comedy           7919 non-null   int64
 56  genre_crime            7919 non-null   int64
 57  genre_documentary      7919 non-null   int64
 58  genre_drama            7919 non-null   int64
 59  genre_family           7919 non-null   int64
 60  genre_fantasy          7919 non-null   int64
 61  genre_history          7919 non-null   int64
 62  genre_horror           7919 non-null   int64
 63  genre_music            7919 non-null   int64
 64  genre_musical          7919 non-null   int64
 65  genre_mystery          7919 non-null   int64
 66  genre_romance          7919 non-null   int64
 67  genre_sci-fi           7919 non-null   int64
 68  genre_sport            7919 non-null   int64
 69  genre_thriller         7919 non-null   int64
 70  genre_unknown          7919 non-null   int64
 71  genre_war              7919 non-null   int64
dtypes: bool(3), float64(10), int64(51), object(8)
memory usage: 4.3+ MB

None

In [23]:
missing_after = df.isnull().sum().sort_values(ascending=False)

display(missing_after[missing_after > 0])

Series([], dtype: int64)

In [24]:
df.to_csv("../data/imdb_features.csv", index=False)

print("Feature engineered dataset saved successfully!")
print("File: ../data/imdb_features.csv")

Feature engineered dataset saved successfully!
File: ../data/imdb_features.csv

In [25]:
import os

os.makedirs("../models", exist_ok=True)

director_avg_rating.to_csv("../models/director_avg_rating.csv")
actor_avg_rating.to_csv("../models/lead_actor_avg_rating.csv")
director_experience.to_csv("../models/director_experience.csv")
actor_experience.to_csv("../models/lead_actor_experience.csv")
genre_frequency.to_csv("../models/genre_frequency.csv")

print("Mapping files saved successfully!")

Mapping files saved successfully!